apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app: mysql
type: Opaque
data:
  mysql-root-password: cm9vdHBhc3N3b3Jk  
  mysql-user: YXBwdXNlcg==               
  mysql-password: YXBwcGFzc3dvcmQ=       

